name: reusable file
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact name
        required: false
        default: dist-files
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: list files
        run: ls
      - name: depolying code
        run: echo " hi how r u "
